/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PageRouteImport } from './routes/$page'
import { Route as ApiPublicCmsLoginRouteImport } from './routes/api.public.cms.login'
import { Route as ApiPublicCmsLogoutRouteImport } from './routes/api.public.cms.logout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PageRoute = PageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCmsLoginRoute = ApiPublicCmsLoginRouteImport.update({
  id: '/api/public/cms/login',
  path: '/api/public/cms/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCmsLogoutRoute = ApiPublicCmsLogoutRouteImport.update({
  id: '/api/public/cms/logout',
  path: '/api/public/cms/logout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$page': typeof PageRoute
  '/api/public/cms/login': typeof ApiPublicCmsLoginRoute
  '/api/public/cms/logout': typeof ApiPublicCmsLogoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$page': typeof PageRoute
  '/api/public/cms/login': typeof ApiPublicCmsLoginRoute
  '/api/public/cms/logout': typeof ApiPublicCmsLogoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$page': typeof PageRoute
  '/api/public/cms/login': typeof ApiPublicCmsLoginRoute
  '/api/public/cms/logout': typeof ApiPublicCmsLogoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$page' | '/api/public/cms/login' | '/api/public/cms/logout'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$page' | '/api/public/cms/login' | '/api/public/cms/logout'
  id:
    | '__root__'
    | '/'
    | '/$page'
    | '/api/public/cms/login'
    | '/api/public/cms/logout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PageRoute: typeof PageRoute
  ApiPublicCmsLoginRoute: typeof ApiPublicCmsLoginRoute
  ApiPublicCmsLogoutRoute: typeof ApiPublicCmsLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$page': {
      id: '/$page'
      path: '/$page'
      fullPath: '/$page'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cms/login': {
      id: '/api/public/cms/login'
      path: '/api/public/cms/login'
      fullPath: '/api/public/cms/login'
      preLoaderRoute: typeof ApiPublicCmsLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cms/logout': {
      id: '/api/public/cms/logout'
      path: '/api/public/cms/logout'
      fullPath: '/api/public/cms/logout'
      preLoaderRoute: typeof ApiPublicCmsLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PageRoute: PageRoute,
  ApiPublicCmsLoginRoute: ApiPublicCmsLoginRoute,
  ApiPublicCmsLogoutRoute: ApiPublicCmsLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
